version: '1.0'

networks:
  videoWebSite:
    external: true
    name: videoWebSite

services:
  mysql:
    container_name: db
    image: mysql:5.7
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=videowebsite
      - TZ=Asia/Shanghai
    ports:
      - "3306:3306"
    networks:
      videoWebSite:
        ipv4_address: 172.31.0.2

  redis:
    container_name: redis
    image: redis:latest
    restart: always
    volumes:
      - /usr/local/redis:/usr/local/redis
    ports:
      - "6379:6379"
    command: redis-server --requirepass 123456
    networks:
      videoWebSite:
        ipv4_address: 172.31.0.3

  elasticsearch:
    image: elasticsearch:8.9.0
    container_name: es
    environment:
      - cluster.name=elasticsearch #设置集群名称为elasticsearch
      - discovery.type=single-node #以单一节点模式启动
      - ES_JAVA_OPTS=-Xms256m -Xmx1024m #设置使用jvm内存大小
      - ELASTIC_PASSWORD=123456   #密码
      - xpack.security.enabled=true
    volumes:
      - /usr/local/elasticsearch/data:/usr/local/elasticsearch/data
    ports:
      - "9200:9200"
    restart: always
    networks:
      videoWebSite:
        ipv4_address: 172.31.0.9

#  kibana:
#    image: kibana:8.9.0
#    container_name: kibana
#    environment:
#      - elasticsearch.hosts=http://es:9200 #设置访问elasticsearch的地址
#      - ELASTICSEARCH_USERNAME=kibana_system
#      - ELASTICSEARCH_PASSWORD=123456  #elastic密码
#      - I18N_LOCALE=zh-CN          #中文
#    ports:
#      - "5601:5601"
#    depends_on:
#      - elasticsearch
#    networks:
#      videoWebSite:
#        ipv4_address: 172.31.0.5

  rabbitmq:
    image: rabbitmq:latest
    container_name: rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=mutezebra
      - RABBITMQ_DEFAULT_PASS=Mute0919..
    ports:
      - "5672:5672"
    restart: always
    networks:
      videoWebSite:
        ipv4_address: 172.31.0.10

  web:
    build: .
    container_name: web
    depends_on:
      - mysql
      - redis
    ports:
      - "8080:9090"
    restart: always
    networks:
      videoWebSite:
        ipv4_address: 172.31.0.6
